# Generated by Django 5.2.1 on 2025-05-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_application_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
