# Generated by Django 5.2.1 on 2025-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_employer_groups_employer_is_active_employer_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
