# Generated by Django 5.2.1 on 2025-05-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_employer_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
